/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/

type CodexConfigOptions = {
  apiKey: string
  endpoint: string
  model: string
  providerName: string
}

const CODEX_PROVIDER_ID = 'newapi'

function singleLine(value: string): string {
  let result = ''
  for (const character of value) {
    const codePoint = character.codePointAt(0) ?? 0
    result += codePoint < 32 || codePoint === 127 ? ' ' : character
  }
  return result.trim()
}

function tomlString(value: string): string {
  return JSON.stringify(singleLine(value))
}

function powershellString(value: string): string {
  return value.replaceAll("'", "''")
}

export function normalizeCodexEndpoint(serverAddress: string): string {
  const normalized = serverAddress.trim().replace(/\/+$/, '')
  if (/\/v1$/i.test(normalized)) return normalized
  return `${normalized}/v1`
}

export function buildCodexConfig(
  options: Omit<CodexConfigOptions, 'apiKey'>
): string {
  const endpoint = normalizeCodexEndpoint(options.endpoint)
  const model = singleLine(options.model)
  const providerName = singleLine(options.providerName) || 'New API'

  return `# Portable Codex configuration generated by New API.
# Codex Desktop creates machine-specific marketplace, MCP runtime, notify,
# browser pipe, and trusted-project entries on each computer.
model_provider = "${CODEX_PROVIDER_ID}"
model = ${tomlString(model)}
model_reasoning_effort = "high"
disable_response_storage = true
approval_policy = "on-request"
sandbox_mode = "workspace-write"
web_search = "live"

[model_providers.${CODEX_PROVIDER_ID}]
name = ${tomlString(providerName)}
base_url = ${tomlString(endpoint)}
wire_api = "responses"

[model_providers.${CODEX_PROVIDER_ID}.auth]
command = "powershell"
args = [
  "-NoProfile",
  "-NonInteractive",
  "-Command",
  "(Get-Content -Raw (Join-Path $env:CODEX_HOME 'auth.json') | ConvertFrom-Json).OPENAI_API_KEY"
]

[features]
apps = true
browser_use = true
browser_use_external = true
computer_use = true
goals = true
in_app_browser = true
multi_agent = true
plugins = true
workspace_dependencies = true

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[plugins."browser@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[desktop]
followUpQueueMode = "queue"
`
}

export function buildCodexAuthJson(apiKey: string): string {
  return JSON.stringify({ OPENAI_API_KEY: apiKey.trim() }, null, 2)
}

export function buildCodexPowerShellSetup(options: CodexConfigOptions): string {
  const endpoint = normalizeCodexEndpoint(options.endpoint)
  const providerBlock = `
[model_providers.${CODEX_PROVIDER_ID}]
name = ${tomlString(options.providerName || 'New API')}
base_url = ${tomlString(endpoint)}
wire_api = "responses"

[model_providers.${CODEX_PROVIDER_ID}.auth]
command = "powershell"
args = [
  "-NoProfile",
  "-NonInteractive",
  "-Command",
  "(Get-Content -Raw (Join-Path $env:CODEX_HOME 'auth.json') | ConvertFrom-Json).OPENAI_API_KEY"
]
`
  const topLevel = `model_provider = "${CODEX_PROVIDER_ID}"
model = ${tomlString(options.model)}
model_reasoning_effort = "high"
disable_response_storage = true`

  return String.raw`$ErrorActionPreference = 'Stop'
$apiKey = '${powershellString(options.apiKey.trim())}'
$codexHome = if ($env:CODEX_HOME) { $env:CODEX_HOME } else { Join-Path $env:USERPROFILE '.codex' }
$configPath = Join-Path $codexHome 'config.toml'
$authPath = Join-Path $codexHome 'auth.json'
$stamp = Get-Date -Format 'yyyyMMdd-HHmmss'

New-Item -ItemType Directory -Force -Path $codexHome | Out-Null
foreach ($path in @($configPath, $authPath)) {
  if (Test-Path $path) {
    Copy-Item -LiteralPath $path -Destination "$path.newapi-$stamp.bak" -Force
  }
}

$auth = if (Test-Path $authPath) {
  Get-Content -Raw -LiteralPath $authPath | ConvertFrom-Json
} else {
  [pscustomobject]@{}
}
$auth | Add-Member -NotePropertyName OPENAI_API_KEY -NotePropertyValue $apiKey -Force
$auth | ConvertTo-Json -Depth 100 | Set-Content -LiteralPath $authPath -Encoding UTF8

$existing = if (Test-Path $configPath) {
  Get-Content -Raw -LiteralPath $configPath
} else {
  ''
}
$keptLines = [System.Collections.Generic.List[string]]::new()
$section = ''
$skipSection = $false
foreach ($line in ($existing -split '\r?\n')) {
  if ($line -match '^\s*\[([^]]+)\]\s*$') {
    $section = $Matches[1]
    $skipSection = $section -eq 'model_providers.${CODEX_PROVIDER_ID}' -or $section.StartsWith('model_providers.${CODEX_PROVIDER_ID}.')
  }
  if ($skipSection) { continue }
  if ($section -eq '' -and $line -match '^\s*(model_provider|model|model_reasoning_effort|disable_response_storage)\s*=') {
    continue
  }
  $keptLines.Add($line)
}

$topLevel = @'
${topLevel}
'@
$providerBlock = @'
${providerBlock.trim()}
'@
$newLine = [Environment]::NewLine
$updated = $topLevel.Trim() + $newLine + $newLine + (($keptLines -join $newLine).Trim()) + $newLine + $newLine + $providerBlock.Trim() + $newLine
$updated | Set-Content -LiteralPath $configPath -Encoding UTF8

$featureNames = @('apps', 'browser_use', 'browser_use_external', 'computer_use', 'goals', 'in_app_browser', 'multi_agent', 'plugins', 'workspace_dependencies')
foreach ($feature in $featureNames) {
  & codex features enable $feature | Out-Null
  if ($LASTEXITCODE -ne 0) { Write-Warning "Codex feature was not enabled: $feature" }
}

$plugins = @('browser@openai-bundled', 'chrome@openai-bundled', 'computer-use@openai-bundled', 'visualize@openai-bundled')
foreach ($plugin in $plugins) {
  & codex plugin add $plugin --json | Out-Null
  if ($LASTEXITCODE -ne 0) { Write-Warning "Codex plugin was not installed: $plugin" }
}

& codex doctor --summary
Write-Host 'Codex configuration installed. Restart Codex Desktop and Codex CLI.' -ForegroundColor Green
`
}

function encodeUtf16LeBase64(value: string): string {
  const bytes = new Uint8Array(value.length * 2)
  for (let index = 0; index < value.length; index += 1) {
    const codeUnit = value.charCodeAt(index)
    bytes[index * 2] = codeUnit & 0xff
    bytes[index * 2 + 1] = codeUnit >> 8
  }

  let binary = ''
  for (const byte of bytes) binary += String.fromCharCode(byte)
  return btoa(binary)
}

export function buildCodexWindowsInstaller(
  options: CodexConfigOptions
): string {
  const encoded = encodeUtf16LeBase64(buildCodexPowerShellSetup(options))
  return `@echo off\r\nchcp 65001 >nul\r\npowershell.exe -NoProfile -ExecutionPolicy Bypass -EncodedCommand ${encoded}\r\nset EXIT_CODE=%ERRORLEVEL%\r\necho.\r\npause\r\nexit /b %EXIT_CODE%\r\n`
}
